# Dockerfile for running java application
FROM anapsix/alpine-java
LABEL maintainer="devopsuser@gmail.com"
COPY devopsProject-1.0-jar-with-dependencies.jar /home/hari/Documents/dockerProject/devopsProject-1.0-jar-with-dependencies.jar
CMD ["java", "-jar", "/home/hari/Documents/dockerProject/devopsProject-1.0-jar-with-dependencies.jar","78","99","83","92"]
