apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-system-deployment   # <== This name must not be empty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-system
  template:
    metadata:
      labels:
        app: grade-system
    spec:
      containers:
      - name: grade-system
        image: devops_project:1.0
        ports:
        - containerPort: 8080
